import Head from "next/head";
import { getSession, signIn, signOut } from "next-auth/react";
import Sidebar from "./../components/Sidebar";

const Home = ({ session }) => {
  console.log("Home function: ", session);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main>Home</main> */}
      <Sidebar />

      <footer></footer>
    </div>
  );
};

export default Home;

/* export async function getServerSideProps(context) {
  try {
    // client.db() will be the default database passed in the MONGODB_URI
    // You can change the database by calling the client.db() function and specifying a database like:
    // const db = client.db("myDatabase");
    // Then you can execute queries against your database like so:
    // db.find({}) or any of the MongoDB Node Driver commands

    //const { db } = await connectToDatabase();

    await clientPromise;
    return {
      props: { isConnected: true },
    };
  } catch (e) {
    console.error(e);
    return {
      props: { isConnected: false },
    };
  }
}
 */

export const getServerSideProps = async (context) => {
  const session = await getSession(context);

  console.log("Get Server side: ", session);

  if (!session) {
    return {
      redirect: {
        destination: "/ingreso",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
};
